### ISSUE TITLE
Unfork the repo

### ISSUE THREAD

**Issue by Sija** [crystal-community/timecop.cr#11]
Since the upstream is no longer maintained, I suggest to unfork the repo (you can do it from here -> https://support.github.com/contact?flow=detach_fork&subject=Detach%20Fork&tags=rr-forks). It can be done only by the repo admin.

**Comment by robacarp** [comment]
I’m in favor. I was looking into this the other day because the default behavior for a new pull is to open it against the upstream rather than master.

**Comment by Sija** [comment]
@robacarp Same here, had to fiddle with the url in order to open a new PR... 🤯

**Comment by robacarp** [comment]
alright, i've completed the request

**Comment by robacarp** [comment]
Seems resolved now.
